const fs = require('node:fs');
const path = require('node:path');
const YAML = require('yaml');
const {root, readSource} = require('./source-files.cjs');
const {build: buildPresentation, layouts} = require('./build-signature.cjs');

function modules() {
  const folders = fs.readdirSync(root, {withFileTypes: true}).filter(entry => entry.isDirectory()).map(entry => entry.name);
  for (const folder of folders) {
    if (fs.existsSync(path.join(root, folder, 'dist', folder + '.yaml')) && !fs.existsSync(path.join(root, folder, 'src/module.yaml')))
      throw new Error('Missing module source: ' + folder + '/src/module.yaml');
  }
  return folders.filter(folder => fs.existsSync(path.join(root, folder, 'src/module.yaml'))).sort();
}

async function build(folder) {
  const layout = folder.replace(/^signature-/, '');
  if (layouts.includes(layout)) return buildPresentation(layout);
  const definition = YAML.parse(readSource(folder + '/src/module.yaml'));
  if (!definition || typeof definition !== 'object' || typeof definition.version !== 'string' || Object.hasOwn(definition, 'code'))
    throw new Error(folder + '/src/module.yaml must declare metadata with a string version, without code');
  definition.code = readSource(folder + '/src/code.css').replaceAll('@@MODULE_VERSION@@', definition.version);
  if (/\/\* @include\b|@@[A-Z_]+@@/.test(definition.code)) throw new Error('Unresolved source directive in ' + folder);
  // Bubble evaluates this field as a template literal; compile without running
  // it to catch syntax errors before publishing any distribution.
  new Function('hass', 'onTeardown', 'renderTemplate', 'return `' + definition.code + '`;');
  const id = folder.replaceAll('-', '_');
  const content = '# Generated by npm run build:modules. Edit src files, then regenerate.\n'
    + YAML.stringify({[id]: definition}, {lineWidth: 0, blockQuote: 'literal'});
  return {file: folder + '/dist/' + folder + '.yaml', content};
}

async function main() {
  const check = process.argv.includes('--check');
  // Build everything before writing, so an invalid source does not leave a
  // partially regenerated set of modules.
  const outputs = [];
  for (const folder of modules()) outputs.push(await build(folder));
  for (const output of outputs) {
    const destination = path.join(root, output.file);
    if (check) {
      if (!fs.existsSync(destination) || fs.readFileSync(destination, 'utf8') !== output.content)
        throw new Error(output.file + ' is stale; run npm run build:modules');
    } else {
      fs.mkdirSync(path.dirname(destination), {recursive: true});
      fs.writeFileSync(destination, output.content);
    }
    console.log((check ? 'Verified ' : 'Built ') + output.file + ' (' + Buffer.byteLength(output.content) + ' bytes)');
  }
}

if (require.main === module) main().catch(error => {console.error(error);process.exitCode = 1;});
module.exports = {build, modules};
